---
title: "Week-9"
author: "Tan Ee Xuan"
date: "2023-10-18"
output: html_document
---

Slide 8
```{r, echo=TRUE, eval=TRUE}
library(tidyverse)

tidydata <- tribble(
  ~country, ~year, ~cases, ~population,
  "Afghanistan", 1999, 745, 19987071,
  "Afghanistan", 2000, 2666, 20595360,
  "Brazil", 1999, 37737, 172006362,
  "Brazil", 2000, 80488, 174504898,
  "China", 1999, 212258, 1272915272,
  "China", 2000, 213766, 1280428583
  )

tidydata
```

```{r, echo=TRUE, eval=TRUE}
nontidydata <- tribble(
  ~country,~year,~rate,
  "Afghanistan", 1999, "745/19987071",
  "Afghanistan", 2000, "2666/20595360",
  "Brazil", 1999, "37737/172006362",
  "Brazil", 2000, "80488/174504898",
  "China", 1999, "212258/1272915272",
  "China", 2000, "213766/1280428583")

nontidydata
```

Slide 11
```{r, echo=TRUE, eval=TRUE}
nontidydata

tidieddata <-nontidydata %>%
  separate(rate, into = c("cases",
                          "population"),
           sep = "/")

tidieddata
```

Slide 12
```{r, echo=TRUE, eval=TRUE}
newtidieddata <- tidieddata %>%
  pivot_longer(
    cols = cases:population,
    names_to = "measurement",
    values_to = "value"
  )

newtidieddata
```

Slide 14
```{r, echo=TRUE, eval=TRUE}
df <- tribble(
  ~id, ~bp1, ~bp2,
  "A", 100, 120,
  "B", 140, 115,
  "C", 120, 125
)

df

df %>%
  pivot_longer(
    cols = bp1:bp2,
    names_to = "measurement",
    values_to = "value"
  )
```

Slide 18
```{r, echo=TRUE, eval=TRUE}
newtidieddata

newtidieddata %>%
  pivot_wider(names_from = "measurement",
              values_from = "value")
```

Slide 19
```{r, echo=TRUE, eval=TRUE}
df <- tribble(
  ~id, ~measurement, ~value,
  "A", "bp1", 100,
  "B", "bp1", 140,
  "B", "bp2", 115,
  "A", "bp2", 120,
  "A", "bp3", 105
)

df

df %>%
  pivot_wider(
    names_from = measurement,
    values_from = value
  )
```
Challenge 

Question 1:
```{r, echo=TRUE, eval=TRUE}
library(tidyverse)

newbillboard <- billboard %>%
  pivot_longer(
    cols = starts_with("wk"),
    names_to = "week",
    values_to = "rank",
    values_drop_na = TRUE
  ) %>%
  mutate(week = parse_number(week))

newbillboard

ggplot(newbillboard, 
       aes(y = rank, x = week, group = track)) +
  geom_line()
```