---
title: "Challenge-7"
author: "Tan Ee Xuan"
date: "2023-10-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

PART 1
```{r, eval=TRUE,echo=TRUE}
library(tidyverse)
library(palmerpenguins)
glimpse(penguins)
```
```{r, eval=TRUE,echo=TRUE}
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     colour = species,
                    )) + 

#aes function will allocate the variable (in this case bill_depth_mm and bill_length_mm) to the x and y axis. We can also change the colour of the dots according to the species variable.

       geom_point() +

#geom_point allows data points to be plotted on the graph

  labs(title = "Bill Depth and Length",
       subtitle = "Dimensions for Adelie,
Chinstrap, and Gentoo Penguins",

#labs allows us to label the graph, i.e. the title and subtitles of the graph. 

x = "Bill depth (mm)",
y = "Bill length (mm)",

#We can also change the name of the x and y axis to be different from the initial variable name.

colour = "Species",

#change the name of the legend from its initial variable name

caption = "Source: Palmer Station LTER / palmerpenguins package") + 

#allows us to write below the graph to credit its source

scale_colour_viridis_d()

#changes the colour of the points for the colour blind 

```

```{r, eval=TRUE,echo=TRUE}
ggplot(penguins,
       aes(x = bill_depth_mm,
           y = bill_length_mm,
           colour = species)) +
  geom_point() +
  scale_colour_viridis_d()
```
```{r, eval=TRUE,echo=TRUE}
ggplot(penguins) + aes(x = bill_depth_mm, y = bill_length_mm,
colour = species, shape = island) +
# shape = island will change the shape of the data point according to the island variable
geom_point() + scale_colour_viridis_d()
```

```{r, eval=TRUE,echo=TRUE}
ggplot(penguins) + 
  aes(x = bill_depth_mm, y = bill_length_mm,
colour = species, shape = species) +
# shape = species will change the shape of the data point according to the species variable
geom_point() + scale_colour_viridis_d()
```
```{r, eval=TRUE,echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
shape = species, size = body_mass_g, 
#size = body_mass_g will change the size of the data point according to the magnitude of the body mass
alpha = flipper_length_mm
#alpha = flipper_length_mm will change the shade/transparency of the data point according to the magnitude of the flipper length
)) +
geom_point() + scale_colour_viridis_d()
```
For Mapping, the size and alpha of the data points are determined by the values of the variable in the data
```{r, eval=TRUE, echo=TRUE}
ggplot(penguins) +
aes(x = bill_depth_mm,
y = bill_length_mm,
size = body_mass_g,
alpha = flipper_length_mm) +
geom_point()
```
For Setting, the size and alpha of the data points are not determined by the values of the variable in the data
```{r, eval=TRUE, echo=TRUE}
ggplot(penguins) +
aes(x = bill_depth_mm,
y = bill_length_mm) +
geom_point(size = 2, alpha = 0.5)
```

```{r, eval=TRUE, echo=TRUE}
ggplot(penguins) +
aes(x = bill_depth_mm,
y = bill_length_mm) +
geom_point() +
facet_grid(species ~ island)
```
```{r, eval=TRUE, echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
facet_grid(species ~ sex)
```
```{r, eval=TRUE, echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
facet_grid(sex ~ species)
```
```{r, eval=TRUE, echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
facet_wrap(~ species)
```

```{r, eval=TRUE, echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
facet_wrap(~ species, ncol = 2)
```
```{r, eval=TRUE, echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
facet_grid(. ~ species)
```

```{r, eval=TRUE, echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
geom_point() + facet_grid(species ~ sex) + scale_color_viridis_d()
```

```{r, eval=TRUE, echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
geom_point() + facet_grid(species ~ sex) + scale_color_viridis_d() +
guides(color = "none")
```

PART 2
```{r, eval=TRUE, echo=TRUE}
library(openintro)
glimpse(loans_full_schema)
```
```{r, eval=TRUE, echo=TRUE}
loans <- loans_full_schema %>%
select(loan_amount, interest_rate, term, grade,
state, annual_income, homeownership, debt_to_income)
glimpse(loans)
```

HISTOGRAM
```{r, eval=TRUE, echo=TRUE}
ggplot(loans) + aes(x = loan_amount) +
geom_histogram()
```

```{r, eval=TRUE, echo=TRUE}
# binwidth = 1000
ggplot(loans, aes(x = loan_amount)) +
geom_histogram(binwidth = 1000)
```

```{r, eval=TRUE, echo=TRUE}
# binwidth = 5000
ggplot(loans, aes(x = loan_amount)) +
geom_histogram(binwidth = 5000)
```

```{r, eval=TRUE, echo=TRUE}
# binwidth = 20000
ggplot(loans, aes(x = loan_amount)) +
geom_histogram(binwidth = 20000)
```

```{r, eval=TRUE, echo=TRUE}
ggplot(loans, aes(x = loan_amount)) + 
  geom_histogram(binwidth = 5000) +
  labs(x = "Loan amount ($)", y = "Frequency", title = "Amounts of Lending Club loans" )
```

```{r, eval=TRUE, echo=TRUE}
ggplot(loans, 
       aes(x = loan_amount, fill = homeownership)) +
  geom_histogram(binwidth = 5000, alpha = 0.5) +
  labs(x = "Loan amount ($)",y = "Frequency",title = "Amounts of Lending Club loans")
```

```{r, eval=TRUE, echo=TRUE}
ggplot(loans, 
       aes(x = loan_amount, fill = homeownership)) + 
  geom_histogram(binwidth = 5000) +
  labs(x = "Loan amount ($)",y = "Frequency",title = "Amounts of Lending Club loans") +
  facet_wrap(~ homeownership, nrow = 3)
```

DENSITY
```{r, eval=TRUE, echo=TRUE}
ggplot(loans, aes(x = loan_amount)) +
  geom_density()
```

```{r, eval=TRUE, echo=TRUE}
ggplot(loans, aes(x = loan_amount)) +
  geom_density(adjust = 0.5)
```

```{r, eval=TRUE, echo=TRUE}
ggplot(loans, aes(x = loan_amount)) +
  geom_density(adjust = 1) # default bandwidth
```

```{r, eval=TRUE, echo=TRUE}
ggplot(loans, aes(x = loan_amount)) +
  geom_density(adjust = 2) # default bandwidth
```

```{r, eval=TRUE, echo=TRUE}
ggplot(loans, aes(x = loan_amount)) +
  geom_density(adjust = 2) +
  labs( x = "Loan amount ($)", y = "Density", title = "Amounts of Lending Club loans" )
```

```{r, eval=TRUE, echo=TRUE}
ggplot(loans, aes(x = loan_amount, fill = homeownership)) +
  geom_density(adjust = 2, alpha = 0.5) +
  labs(x = "Loan amount ($)",y = "Density",title = "Amounts of Lending Club loans", fill = "Homeownership")
```

BOXPLOT

```{r, eval=TRUE, echo=TRUE}
ggplot(loans, aes(x = interest_rate)) +
  geom_boxplot()
```

```{r, eval=TRUE, echo=TRUE}
ggplot(loans, aes(x = annual_income)) +
  geom_boxplot()
```

```{r, eval=TRUE, echo=TRUE}
ggplot(loans, 
       aes(x = interest_rate)) +
  geom_boxplot() +
  labs(x = "Interest rate (%)",y = NULL,
       title = "Interest rates of Lending Club loans") +
  theme( axis.ticks.y = element_blank(), axis.text.y = element_blank() )
```

```{r, eval=TRUE, echo=TRUE}
ggplot(loans, 
       aes(x = interest_rate,
                  y = grade)) +
  geom_boxplot() +
  labs(x = "Interest rate (%)",y = "Grade",title = "Interest rates of Lending Club loans",subtitle = "by grade of loan")
```

SCATTERPLOT
```{r, eval=TRUE, echo=TRUE}
ggplot(loans, 
       aes(x = debt_to_income, y = interest_rate)) +
  geom_point()
```

HEX PLOT
```{r, eval=TRUE, echo=TRUE}
ggplot(loans, 
       aes(x = debt_to_income, y = interest_rate)) +
  geom_hex()
```

```{r, eval=TRUE, echo=TRUE}
ggplot(loans %>% filter(debt_to_income < 100),
       aes(x = debt_to_income, y = interest_rate)) +
  geom_hex()
```

PART 3:
BAR PLOT
```{r, eval=TRUE, echo=TRUE}
ggplot(loans, aes(x = homeownership)) +
  geom_bar()
```

SEGMENTED BAR PLOT
```{r, eval=TRUE, echo=TRUE}
ggplot(loans, 
       aes(x = homeownership,
           fill = grade)) +
  geom_bar()
```

```{r, eval=TRUE, echo=TRUE}
ggplot(loans, 
       aes(x = homeownership, fill = grade)) +
  geom_bar(position = "fill")
```

```{r, eval=TRUE, echo=TRUE}
ggplot(loans, aes(y = homeownership, fill = grade)) + 
  geom_bar(position = "fill") +
  labs( x = "Proportion", y = "Homeownership", fill = "Grade", title = "Grades of Lending Club loans", subtitle = "and homeownership of lendee")
```

PART 4
VIOLIN PLOTS
```{r, eval=TRUE, echo=TRUE}
ggplot(loans, aes(x = homeownership, y = loan_amount)) +
  geom_violin()
```
RIDGE PLOTS
```{r, eval=TRUE, echo=TRUE}
library(ggridges)
ggplot(loans, aes(x = loan_amount, y = grade, fill = grade, color = grade)) +
  geom_density_ridges(alpha = 0.5)
```

```{r, eval=TRUE, echo=TRUE}

```

```{r, eval=TRUE, echo=TRUE}

```

```{r, eval=TRUE, echo=TRUE}

```

```{r, eval=TRUE, echo=TRUE}

```

```{r, eval=TRUE, echo=TRUE}

```